In [187]:
# numpy 줄 맞추기
import numpy as np

matrix=np.array(range(6)).reshape(2,3)
count=1

# 1. 출력이 밀려 줄이 맞추어 지지 않는다.
print("{}. {} 2*3 행렬".format(count,matrix)) 
count+=1

# 2. array2string의 prefix를 이용해 앞줄을 맞출 수 있다.
print("{}. {} 2*3 행렬".format(count,np.array2string(matrix,prefix="%d. "%count))) 
count+=1

# 3. 자리수만 채워도 제대로 동작한다.
print("{}. {} 2*3 행렬".format(count,np.array2string(matrix,prefix="   "))) 
count+=1

# 4. numpy 나란히 출력하기 - 3차원 이하의 배열
def print_matrix(matrix):
    import numpy as np
    align_count=0
    temp_count=0
    rjust_size=len(str(np.max(matrix)))
    def print_main(temp_matrix):
        nonlocal align_count, matrix, temp_count
        temp_matrix_size=temp_matrix.shape
        if len(temp_matrix_size)==1:
            align_count+=1
            if align_count>=2:
                matrix_size=matrix.shape
                align_cal=len(matrix_size)-1
                if 1==align_count%matrix_size[align_cal-1]:
                    pass
                else: 
                    for i in range(align_cal):
                        print(" ",end="")
            for i in range(temp_matrix_size[0]):
                if i==0: print("["+str(temp_matrix[i]).rjust(rjust_size),end=" ")
                elif i==temp_matrix_size[0]-1: print(str(temp_matrix[i]).rjust(rjust_size)+"]",end="")
                else: print(str(temp_matrix[i]).rjust(rjust_size), end=" ")
        else:
            for i in range(temp_matrix_size[0]):
                temp_count+=1
                if temp_count>=2: # 4차원 이상의 배열을 출력할 경우 수정해야함.
                    print(" ",end="")
                    temp_count=0
                if i==0: 
                    print("[",end="")
                    temp_count=0
                print_main(temp_matrix[i])
                if i==temp_matrix_size[0]-1: 
                    print("]",end="")
                    temp_count=0
                else: 
                    print("")
                    temp_count=0
    print_main(matrix)

# matrix[0,0]=133
# matrix=np.array(range(24)).reshape(2,3,4)
print_matrix(matrix)

1. [[0 1 2]
 [3 4 5]] 2*3 행렬
2. [[0 1 2]
    [3 4 5]] 2*3 행렬
3. [[0 1 2]
    [3 4 5]] 2*3 행렬
[[0 1 2]
 [3 4 5]]

In [131]:
# numpy를 사용하는 이유- 속도차이
import numpy as np # numpy 모듈을 불러옴 - 주로 행렬, 벡터, 다차원 배열을 처리하기 위해 쓰임

count=1
array=np.array(range(24)) # 1. list, tuple, set 등을 array로 바꿔줌
print("{}. {} {}".format(count,array,type(array)))
count+=1

print("{}. {} {}".format(count,array.shape,type(array.shape))) # 2. array의 크기 반환
count+=1

array=array.reshape(2,3,4)
print("{}. {}".format(count,np.array2string(array,prefix="   "))) # 3. array의 크기 변환
count+=1

print("{}. {}".format(count,array[0,1,2])) # 4. 배열([][])과 달리 [,] 를 이용해 indexing 을 할 수 있다.
count+=1

print("{}. {}".format(count,array[0,1:,:3])) # 5. array도 list처럼 sllicing을 사용할 수 있다.
count+=1

1. [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] <class 'numpy.ndarray'>
2. (24,) <class 'tuple'>
3. [[[ 0  1  2  3]
     [ 4  5  6  7]
     [ 8  9 10 11]]

    [[12 13 14 15]
     [16 17 18 19]
     [20 21 22 23]]]
4. 6
5. [[ 4  5  6]
 [ 8  9 10]]


In [29]:
import numpy as np

# 벡터와 스칼라 연산
x=np.array([1,2,3])
count=1
c=5
print("{}. {}".format(count,x+c)) #  1. 더하기
count+=1

print("{}. {}".format(count,x-c)) #  2. 빼기
count+=1

print("{}. {}".format(count,x*c)) #  3. 곱하기
count+=1

print("{}. {}".format(count,x/c)) #  4. 나누기
count+=1

# 벡터와 벡터 연산
y=np.array([4,5,6])
print("{}. {}".format(count,x+y)) #  5. 더하기
count+=1

print("{}. {}".format(count,x-y)) #  6. 빼기
count+=1

print("{}. {}".format(count,x*y)) #  7. 곱하기
count+=1

print("{}. {}".format(count,x/y)) #  8. 나누기
count+=1

1. [6 7 8]
2. [-4 -3 -2]
3. [ 5 10 15]
4. [0.2 0.4 0.6]
5. [5 7 9]
6. [-3 -3 -3]
7. [ 4 10 18]
8. [0.25 0.4  0.5 ]


In [133]:
import numpy as np

# 행렬 연산
matrix_1=np.array(range(1,5)).reshape([2,2])
matrix_2=np.array(range(5,9)).reshape([2,2])
count=1

print("{}. {}".format(count,np.array2string(matrix_1,prefix="   "))) # 1.
count+=1

print("{}. {}".format(count,np.array2string(matrix_2,prefix="   "))) # 2.
count+=1

print("{}. {}".format(count,np.array2string(matrix_1.dot(matrix_2),prefix="   "))) # 3. 행렬 곱 ver 1
count+=1

print("{}. {}".format(count,np.array2string(matrix_1@matrix_2,prefix="   "))) # 4. 행렬 곱 ver 2
count+=1

print("{}. {}".format(count,np.trace(matrix_1))) # 5. 주대각선의 합 variable.trace()의 형태로도 사용 가능
count+=1

print("{}. {}".format(count,np.linalg.det(matrix_1))) # 6. determinet 겂
count+=1

print("{}. {}".format(count,np.array2string(np.linalg.inv(matrix_1),prefix="   "))) # 7. 역행렬
count+=1

eigenvalue, eigenvector=np.linalg.eig(matrix_1)
print("{}. {}".format(count,eigenvalue)) # 8. 고유값
count+=1

print("{}. {}".format(count,np.array2string(eigenvector,prefix="   "))) # 9. 고유벡터
count+=1

1. [[1 2]
    [3 4]]
2. [[5 6]
    [7 8]]
3. [[19 22]
    [43 50]]
4. [[19 22]
    [43 50]]
5. 5
6. -2.0000000000000004
7. [[-2.   1. ]
    [ 1.5 -0.5]]
8. [-0.37228132  5.37228132]
9. [[-0.82456484 -0.41597356]
    [ 0.56576746 -0.90937671]]
