### 1D Array

In [24]:
import torch
count=1
# tensor 앞의 변수 type에 따라 요소의 type을 바꿀 수 있다. (6.을 이용해 후에 타입을 다시 변경할 수 있다.)
int_tensor_1D=torch.IntTensor([i for i in range(6)])
float_tensor_1D=torch.FloatTensor([i for i in range(6)])
print("{}. {}".format(count,int_tensor_1D)) # 1. type=int
count+=1
print("{}. {}".format(count,float_tensor_1D)) # 2 type=float
count+=1
print("{}. {} {}".format(count,int_tensor_1D.dim(),int_tensor_1D.ndim)) # 3. tensor의 차원
count+=1
print("{}. {} {}".format(count,int_tensor_1D.shape,int_tensor_1D.size())) # 4. tensor의 형태
count+=1
print("{}. {}".format(count,int_tensor_1D[1:-1])) # 5. list와 같이 slice 가능 [주의 2차원부터는 다름]
count+=1
print("{}. {} {}".format(count,int_tensor_1D.float(),float_tensor_1D.int())) # 6. tensor의 타입 변경
count+=1

1. tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)
2. tensor([0., 1., 2., 3., 4., 5.])
3. 1 1
4. torch.Size([6]) torch.Size([6])
5. tensor([1, 2, 3, 4], dtype=torch.int32)
6. tensor([0., 1., 2., 3., 4., 5.]) tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)


### 2D, 3D Array

In [40]:
import torch
count=1
# reshape와 view를 통해 tensor의 차원(형태)를 바꿀 수 있다.
int_tensor_2D=torch.reshape(torch.arange(12),(3,4))
float_tensor_3D=torch.arange(24,dtype=torch.float).view(-1,3,4) # -1을 넣으면 알아서 계산해준다.
print("{}.\n {}".format(count,int_tensor_2D)) # 1.
count+=1
print("{}.\n {}".format(count,float_tensor_3D)) # 2. 
count+=1
print("{}. {} {}".format(count,int_tensor_2D.dim(), float_tensor_3D.ndim)) # 3. tensor의 차원
count+=1
print("{}. {} {}".format(count,int_tensor_2D.shape, float_tensor_3D.size())) # 4. tensor의 형태
count+=1
print("{}. {}".format(count,int_tensor_2D[:,1])) # 5. 2차원 이상 : tensor=[,] list=[][] 
count+=1
print("{}.\n {}".format(count,float_tensor_3D[:,:3,:1])) # 6.
count+=1

1.
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2.
 tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
3. 2 3
4. torch.Size([3, 4]) torch.Size([2, 3, 4])
5. tensor([1, 5, 9])
6.
 tensor([[[ 0.],
         [ 4.],
         [ 8.]],

        [[12.],
         [16.],
         [20.]]])


### Zero & One Array

In [9]:
import torch
count=1
zero_tensor=torch.zeros(6)
one_tensor=torch.ones(2,3)

print("{}. {}".format(count,zero_tensor)) # 1.
count+=1
print("{}.\n {}".format(count,one_tensor)) # 2.
count+=1
print("{}.\n {}".format(count,torch.zeros_like(one_tensor))) # 3. 
count+=1
print("{}. {}".format(count,torch.ones_like(zero_tensor))) # 4.
count+=1

1. tensor([0., 0., 0., 0., 0., 0.])
2.
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
3.
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
4. tensor([1., 1., 1., 1., 1., 1.])


### Operator

In [4]:
import torch
count=1

matrix_1 = torch.FloatTensor([i+1 for i in range(4)]).reshape(2,2)
matrix_2 = torch.FloatTensor([[1], [2]])
print("{}.\n {}".format(count,matrix_1)) # 1. 
count+=1
print("{}.\n {}".format(count,matrix_2)) # 2. 
count+=1
print("{}.\n {}\n {}".format(count,matrix_1.matmul(matrix_2),matrix_1@matrix_2)) # 3. 행렬 곱
count+=1
# 기본적인 사칙연산은 자동으로 tensor의 크기를 조절한다.
print("{}.\n {}".format(count,matrix_1.mul(matrix_2))) # 4. 일반 곱 ver_1 | .mul_()시 matrix_1 값이 바뀜
count+=1
print("{}.\n {}".format(count,matrix_1*matrix_2)) # 5. 일반 곱 ver_2
count+=1
print("{}.\n {}".format(count,matrix_1+matrix_2)) # 6. 일반 합
count+=1
print("{}.\n {}".format(count,matrix_1-matrix_2)) # 7. 일반 차
count+=1
print("{}.\n {}".format(count,matrix_1/matrix_2)) # 8. 일반 나누기
count+=1

1.
 tensor([[1., 2.],
        [3., 4.]])
2.
 tensor([[1.],
        [2.]])
3.
 tensor([[ 5.],
        [11.]])
 tensor([[ 5.],
        [11.]])
4.
 tensor([[1., 2.],
        [6., 8.]])
5.
 tensor([[1., 2.],
        [6., 8.]])
6.
 tensor([[2., 3.],
        [5., 6.]])
7.
 tensor([[0., 1.],
        [1., 2.]])
8.
 tensor([[1.0000, 2.0000],
        [1.5000, 2.0000]])


### Squeeze & Unsqueeze

In [3]:
import torch
count=1
# Squeeze는 size 중 하나가 1일 떄 사용가능
test_tensor=torch.arange(2).view(-1,2)
print("{}. {} {}".format(count,test_tensor,test_tensor.shape)) # 1. Squeeze 전 행렬
count+=1
test_tensor=test_tensor.squeeze()
print("{}. {} {}".format(count,test_tensor,test_tensor.shape)) # 2. Squeeze 후 행렬
count+=1

temp_tensor=test_tensor.unsqueeze(0)
print("{}. {} {}".format(count,temp_tensor,temp_tensor.shape)) # 3. 차원 0에 Unsqueeze 후 행렬
count+=1

temp_tensor=test_tensor.unsqueeze(1)
print("{}.\n {} {}".format(count,temp_tensor,temp_tensor.shape)) # 4. 차원 1에 Unsqueeze 후 행렬
count+=1

1. tensor([[0, 1]]) torch.Size([1, 2])
2. tensor([0, 1]) torch.Size([2])
3. tensor([[0, 1]]) torch.Size([1, 2])
4.
 tensor([[0],
        [1]]) torch.Size([2, 1])


### Concatenation & Stacking

In [37]:
import torch
count=1

test_tensor_1=torch.FloatTensor([[1, 2], [3, 4]])
test_tensor_2=torch.FloatTensor([[5, 6], [7, 8]])
print("{}.\n {} {}".format(count,test_tensor_1,test_tensor_1.shape)) # 1.
count+=1
print("{}.\n {} {}".format(count,test_tensor_2,test_tensor_2.shape)) # 2.
count+=1

temp_tensor=torch.cat([test_tensor_1, test_tensor_2], dim=0)
print("{}.\n {} {}".format(count,temp_tensor,temp_tensor.shape)) # 3. 차원 0에 Concatenation 후 행렬
count+=1
temp_tensor=torch.cat([test_tensor_1, test_tensor_2], dim=1)
print("{}.\n {} {}".format(count,temp_tensor,temp_tensor.shape)) # 4. 차원 1에 Concatenation 후 행렬
count+=1

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print("{}. {} {} {} {}".format(count,x,y,z,z.shape)) # 5.
count+=1
temp_tensor=torch.stack([x, y, z])
print("{}.\n {} {}".format(count,temp_tensor,temp_tensor.shape)) # 6. 차원 0에 Stacking 후 행렬
count+=1
temp_tensor=torch.stack([x, y, z], dim=1)
print("{}.\n {} {}".format(count,temp_tensor,temp_tensor.shape)) # 7. 차원 1에 Stacking 후 행렬

1.
 tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])
2.
 tensor([[5., 6.],
        [7., 8.]]) torch.Size([2, 2])
3.
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.Size([4, 2])
4.
 tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]]) torch.Size([2, 4])
5. tensor([1., 4.]) tensor([2., 5.]) tensor([3., 6.]) torch.Size([2])
6.
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]]) torch.Size([3, 2])
7.
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])
