In [1]:
# 기본 행렬
import numpy as np

count=1
matrix=np.array([1,2,3]) # 1. list를 행렬의 형태로 변환
print(f"{count}. {matrix}")
count+=1

matrix=np.arange(10) # 2. 연속하는 행렬 생성
print(f"{count}. {matrix}")
count+=1

matrix=np.arange(3,9,3) # 3. 등차수열 행렬 생성 시작과 끝 지정 size입력 없을 시 자동 1로 고정
print(f"{count}. {matrix}")
count+=1

matrix=np.linspace(3,9,6) # 4. 시작과 끝을 분할하는 행렬 생성
print(f"{count}. {matrix}")
count+=1

matrix=np.zeros(10) # 5. 요소가 0인 행렬 생성
print(f"{count}. {matrix}")
count+=1

matrix=np.ones(10) # 6. 요소가 1인 행렬 생성
print(f"{count}. {matrix}")
count+=1

matrix= np.r_[np.ones(2),np.zeros(2)] # 7. 행렬 붙이기 np.append(ex_num1,ex_num3) 도 가능
print(f"{count}. {matrix}")
count+=1

matrix=np.arange(10) # 8. 행렬의 크기 변환
matrix=matrix.reshape(2,5)
print(f"{count}. {matrix}")
count+=1


1. [1 2 3]
2. [0 1 2 3 4 5 6 7 8 9]
3. [3 6]
4. [3.  4.2 5.4 6.6 7.8 9. ]
5. [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
6. [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
7. [1. 1. 0. 0.]
8. [[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
# 랜덤 데이터
import numpy as np

count=1
matrix=np.random.rand(2,3) # 1. 0~1사이의 균일한 분포
print(f"{count}. {matrix}")
count+=1

matrix=np.random.randint(1,10,[2,3]) # 2. start에서 end까지의 임의의 정수값으로 이뤄진 size 크기의 행렬
print(f"{count}. {matrix}")
count+=1

matrix=np.random.randn(30) # 3. 평균 0 분산 1의 가우스 분포
print(f"{count}. {matrix}")
count+=1

mean=np.mean(matrix) # 4. 평균 
print(f"{count}. {mean}")
count+=1

std=np.std(matrix) # 5. 표준편차
print(f"{count}. {std}")
count+=1

'''
matrix=np.random.randn(5)
np.save('datafile_ex1.npy',matrix) # 행렬 저장
matrix=[]
print(matrix)
matrix=np.load('datafile_ex1.npy')
print(matrix)
'''

1. [[0.52848872 0.46632602 0.88863435]
 [0.74249061 0.96175442 0.72679531]]
2. [[8 7 2]
 [4 9 4]]
3. [ 0.66602166 -0.31005078  0.69902945  0.6362468   1.40721138 -0.43254542
 -0.24681341  1.34449555  0.14747896  0.3429444  -0.90404902 -0.38139504
  0.70117904  1.00325574 -1.00738632 -1.2757906   0.39454192  0.30970829
  0.14908595  0.70276386 -0.62396463 -0.30075077 -1.36801795  1.10078104
 -0.08789926 -0.21374382 -0.50100705 -0.85789499  0.24486591  2.28698107]
4. 0.12084273255877812
5. 0.835365832210591


"\nmatrix=np.random.randn(5)\nnp.save('datafile_ex1.npy',matrix) # 행렬 저장\nmatrix=[]\nprint(matrix)\nmatrix=np.load('datafile_ex1.npy')\nprint(matrix)\n"

In [6]:
# 특수 연산
import numpy as np

count=1
matrix=np.arange(10) 
print(f"{count}. {matrix} {np.exp(matrix)}") # 1. e(자연상수)의 거듭제곱 연산
count+=1

1. [0 1 2 3 4 5 6 7 8 9] [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
