In [1]:
import torch

count=1
x_train=torch.FloatTensor([[1], [2], [3]])
y_train=torch.FloatTensor([[1], [2], [3]])
W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
hypothesis=x_train*W+b
cost=torch.mean((hypothesis-y_train)**2)

print("{}.\n {} {}\n {} {}".format(count,x_train,x_train.shape,y_train,y_train.shape)) # 1. 학습데이터
count+=1
print("{}. {} {} {} {}".format(count,W,b,W.item(),b.item())) # 2. 선형모델 기울기와 절편 (tensor.item() 값만 가져오기[*단일 tensor만 가능])
count+=1
print("{}.\n {}".format(count,hypothesis)) # 3. y_train의 예측값
count+=1
print("{}. {}".format(count,cost)) # 4. y_train과 예측값의 오차
count+=1

optimizer=torch.optim.SGD([W, b], lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

hypothesis=x_train*W+b
cost=torch.mean((hypothesis-y_train)**2)
print("{}. {} {}".format(count,W.item(),b.item())) # 5. 학습 후 선형모델 기울기와 절편
count+=1
print("{}.\n {}".format(count,hypothesis)) # 6. 학습 후 y_train의 예측값
count+=1
print("{}. {}".format(count,cost)) # 7. 학습 후 y_train과 예측값의 오차
count+=1

1.
 tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])
 tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])
2. tensor([0.], requires_grad=True) tensor([0.], requires_grad=True) 0.0 0.0
3.
 tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
4. 4.666666507720947
5. 0.09333334118127823 0.03999999910593033
6.
 tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)
7. 3.6927406787872314


In [4]:
import torch

x_train=torch.FloatTensor([[1], [2], [3]])
y_train=torch.FloatTensor([[1], [2], [3]])
W=torch.zeros(1, requires_grad=True)
b=torch.zeros(1, requires_grad=True)
optimizer=torch.optim.SGD([W, b], lr=0.01)
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis=x_train*W+b
    cost=torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1000 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100/1000 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200/1000 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300/1000 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400/1000 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500/1000 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600/1000 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700/1000 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800/1000 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900/1000 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000158


In [4]:
import torch

count=1
class LinearRegressionModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=torch.nn.Linear(1,1) # (input,output)

    def forward(self,x):
        return self.linear(x)

x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

model=LinearRegressionModel()
hypothesis=model(x_train)
cost=torch.nn.functional.mse_loss(hypothesis,y_train)

print("{}.\n {} {}\n {} {}".format(count,x_train,x_train.shape,y_train,y_train.shape)) # 1. 학습데이터
count+=1
print("{}.\n {}".format(count,hypothesis)) # 2. y_train의 예측값
count+=1
print("{}. {}".format(count,cost)) # 3. y_train과 예측값의 오차
count+=1

1.
 tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])
 tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])
2.
 tensor([[-0.5580],
        [-0.2719],
        [ 0.0143]], grad_fn=<AddmmBackward>)
3. 5.501039981842041


In [8]:
import torch

class LinearRegressionModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=torch.nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)

x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

model=LinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=torch.nn.functional.mse_loss(prediction,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        params=list(model.parameters())
        W=params[0].item()
        b=params[1].item()
        print('Epoch {:4d}/{} W: {:.3f},b: {:.3f} Cost: {:.6f}'.format(
            epoch,nb_epochs,W,b,cost.item()
        ))

Epoch    0/1000 W: -0.172, b: 0.355 Cost: 6.139223
Epoch  100/1000 W: 0.748, b: 0.573 Cost: 0.047355
Epoch  200/1000 W: 0.802, b: 0.451 Cost: 0.029262
Epoch  300/1000 W: 0.844, b: 0.354 Cost: 0.018082
Epoch  400/1000 W: 0.878, b: 0.278 Cost: 0.011174
Epoch  500/1000 W: 0.904, b: 0.219 Cost: 0.006905
Epoch  600/1000 W: 0.924, b: 0.172 Cost: 0.004267
Epoch  700/1000 W: 0.941, b: 0.135 Cost: 0.002637
Epoch  800/1000 W: 0.953, b: 0.106 Cost: 0.001629
Epoch  900/1000 W: 0.963, b: 0.084 Cost: 0.001007
Epoch 1000/1000 W: 0.971, b: 0.066 Cost: 0.000622
